### ISSUE TITLE
webpack 2.1.0-beta.14 Uncaught Exception

### ISSUE THREAD

**Issue by ChristopherBiscardi** [carteb/carte-blanche#363] opened 2016-06-27 18:07 UTC
webpack 2.1.0-beta.14 will throw the following error.

```
CarteBlanche started at /carte-blanche
Uncaught Exception...
TypeError: d.getWarnings is not a function
    at <project>/node_modules/webpack/lib/Compilation.js:594:21
    at Array.forEach (native)
    at <project>/node_modules/webpack/lib/Compilation.js:593:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (<project>/node_modules/webpack/lib/Compilation.js:592:9)
    at Compilation.<anonymous> (<project>/node_modules/webpack/lib/Compilation.js:483:8)
    at Array.forEach (native)
    at Compilation.seal (<project>/node_modules/webpack/lib/Compilation.js:482:15)
    at Compiler.<anonymous> (<project>/node_modules/webpack/lib/Compiler.js:431:15)
    at <project>/node_modules/webpack/node_modules/tapable/lib/Tapable.js:152:11
    at Compilation.<anonymous> (<project>/node_modules/webpack/lib/Compilation.js:430:10)
    at <project>/node_modules/webpack/lib/Compilation.js:405:12
    at <project>/node_modules/webpack/lib/Compilation.js:320:10
    at <project>/node_modules/async/lib/async.js:52:16
    at done (<project>/node_modules/async/lib/async.js:246:17)
    at <project>/node_modules/async/lib/async.js:44:16
Uncaught Exception...
undefined
```

I didn't have time to look into why this is happening, but I've narrowed it down to being in the .14 release.

## Temporary Fix

downgrade to `webpack 2.1.0-beta.13`

**Comment by nikgraf** [comment] 2016-06-30 12:18
I briefly looked into the issue. First hints: https://github.com/webpack/webpack/compare/36e4fd2...6748dca#diff-d6308b00976bdf2edefc0f08dd6e1cafR594

**Comment by nikgraf** [comment] 2016-06-30 12:39
@sokra did we do something wrong in Carte Blanche or is a bug of the Beta?

**Comment by nikgraf** [comment] 2016-07-16 07:05
Working on this. We identified the ExtraEntryPlugin as root cause although I'm not sure if it's a bug in webpack or we do something wrong in the ExtraEntryPlugin: https://github.com/carteb/carte-blanche/pull/379

**Comment by sokra** [comment] 2016-07-16 09:03
Looks like the extra-entry-plugin should have a peerDependency to webpack instead of a depenency. And webpack@^2.1.0-beta need to be included.

https://github.com/jantimon/extra-entry-webpack-plugin/blob/master/package.json#L46

**Comment by nikgraf** [comment] 2016-07-16 11:50
This will be resolved with the next release 😄 https://github.com/carteb/carte-blanche/pull/379

**Closed by nikgraf** 2016-07-16 11:50 UTC
Labels: bug

**Comment by ChristopherBiscardi** [comment] 2016-07-18 16:31
👍
